name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: get_release
        
        run: |
          # Fetch release information and extract the release tag
          RELEASE_TAG=$(curl -s https://api.github.com/repos/xCollateral/VulkanMod/releases/latest | jq -r '.tag_name')
          RELEASE_BODY=$(curl -s https://api.github.com/repos/xCollateral/VulkanMod/releases/latest | jq -r '.body')
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "latest release: $RELEASE_TAG"

      - name: Store description
        run: |
          # Store the newly fetched release version in a file
          # echo "${{ steps.get_release.outputs.RELEASE_TAG }}" > release-info
          echo "# This is an unofficial ARM build. No warranty or support is provided for this product. It is provided as-is. Use at your own discretion. /r/n" > release-body.txt
          echo "${{ steps.get_release.outputs.RELEASE_BODY }}" >> release-body.txt
          # echo "Saved ${{ steps.get_release.outputs.RELEASE_TAG }} to release-info"  
  
      - name: Checkout VulkanMod repo
        uses: actions/checkout@v4
        with:
          repository: xCollateral/VulkanMod
          ref: ${{ steps.get_release.outputs.RELEASE_TAG }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: patch
      
      - name: Apply patch
        run: git apply patch/arm.patch
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload new artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_release.outputs.RELEASE_TAG }}
          path: build/libs/*
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*
          body_path: release-body.txt
          tag_name: ${{ steps.get_release.outputs.RELEASE_TAG }}
          make_latest: true