name: Check for new release of VulkanMod

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: lebestnoob/VulkanMod-ARM  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: vulkanmod  # The step ID to refer to later.

      - run: echo "VulkanMod-ARM is at version ${{ steps.vulkanmod.outputs.tag }}"
     
      - name: Get latest release
        id: get_release
        run: |
          # Fetch release information and extract the release tag
          RELEASE_TAG=$(curl -s https://api.github.com/repos/xCollateral/VulkanMod/releases/latest | jq -r '.tag_name')
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "latest release: $RELEASE_TAG"

      - name: Compare with previous release
        id: compare_release
        run: |
          # Read the release info from the downloaded artifact
          echo "previous release: ${{ steps.vulkanmod.outputs.tag }}"

          # Compare the fetched release tag with the previous release tag
          if [ "${{ steps.get_release.outputs.RELEASE_TAG }}" != "${{ steps.vulkanmod.outputs.tag }}" ]; then
            echo "release_changed=true" >> $GITHUB_OUTPUT
            echo "Release changed: true"
          else
            echo "release_changed=false" >> $GITHUB_OUTPUT
            echo "Release changed: false"
          fi

      - name: Call workflow to build code
        if: steps.compare_release.outputs.release_changed == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml